name: oo_license_client
description: OO-License Client SDK for Dart/Flutter - Simple license validation and activation
version: 1.0.0
homepage: https://github.com/onaonbir/oo-license

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  crypto: ^3.0.3
  encrypt: ^5.0.3
  device_info_plus: ^9.1.1

dev_dependencies:
  test: ^1.24.0
